AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  copa-america-partiql-demo

  Sample SAM Template for copa-america-partiql-demo
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CopaAmericaPartiQLDemoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: copa-america-partiql-demo/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        GetTeams:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /teams
            Method: get
        GetMatches:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /matches
            Method: get
        GetTeamDetails:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /teams/{id}
            Method: get
        GetMatchesOfATeam:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /matches/{id}
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CopaAmericaPartiQLDemoApi:
    Description: "API Gateway endpoint URL for Prod stage for getting all teams"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/teams/"
  CopaAmericaPartiQLDemoApiForATeam:
    Description: "API Gateway endpoint URL for Prod stage for getting a team's details"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/teams/Brazil"
  CopaAmericaPartiQLDemoApiMatches:
    Description: "API Gateway endpoint URL for Prod stage for getting all match scores"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/matches/"
  CopaAmericaPartiQLDemoApiMatchesOfATeam:
    Description: "API Gateway endpoint URL for Prod stage for getting a team's match history"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/matches/Brazil"
  CopaAmericaPartiQLDemoFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt CopaAmericaPartiQLDemoFunction.Arn
  CopaAmericaPartiQLDemoIamRole:
    Description: "Implicit IAM Role created for lambda function"
    Value: !GetAtt CopaAmericaPartiQLDemoFunctionRole.Arn
